# ===================================================================
# Magic Split Strategy - Global Configuration
# config.yaml
# ===================================================================

# --- 1. Database Connection ---
database:
  host: 172.21.224.1
  user: root
  password: "@waren2ss"
  database: stocks

# --- 2. Backtest Period & Capital ---
backtest_settings:
  start_date: '2014-08-01'
  end_date: '2025-05-30'
  initial_cash: 100000000
  save_full_trade_history: True  # True로 설정하면 모든 거래 내역을 CSV로 저장합니다.

# --- 3. Magic Split Strategy Parameters ---
strategy_params:
  max_stocks: 24
  order_investment_ratio: 0.02
  additional_buy_drop_rate: 0.06
  sell_profit_rate: 0.16
  additional_buy_priority: 'lowest_order'
  cooldown_period_days: 5 # 매도 후 재매수 방지 기간 (영업일 기준)

  # --- [New] Advanced Risk Management Parameters ---
  stop_loss_rate: -0.40 # 포지션 진입가 대비 최대 손실률 (-15%)
  max_splits_limit: 10 # 최대 분할매수 차수 (10차까지)
  max_inactivity_period: 30      # (정적) 최대 매매 미발생 기간 (일)

# --- 4. Execution Handler Parameters ---
execution_params:
  buy_commission_rate: 0.00015
  sell_commission_rate: 0.00015
  sell_tax_rate: 0.0018

# --- 5. Result & Log Paths ---
paths:
  results_dir: "results/"
  log_dir: "logs/"

# ===================================================================
# 6. Walk-Forward Optimization Settings
# ===================================================================
walk_forward_settings:
  total_folds: 5
  # OOS 기간이 IS 기간보다 며칠 뒤에 시작할지 정의 (시간차)
  # 예: 182일 = IS 시작 후 6개월 뒤에 OOS 시작
  oos_start_offset_days: 182

  # OOS 기간의 '길이' (IS 기간과 같거나 다를 수 있음)
  # 예: 2190일 = OOS 기간의 길이는 6년
  out_of_sample_period_days: 2190

  # 다음 Fold로 넘어갈 때 시작일을 이동시키는 간격
  step_size_days: 182