# ===================================================================
# Magic Split Strategy - Global Configuration
# config.yaml
# ===================================================================

# --- 1. Database Connection ---
database:
  host: 172.21.224.1
  user: root
  password: "@waren2ss"
  database: stocks

# --- 2. Backtest Period & Capital ---
backtest_settings:
  start_date: '2020-03-15'
  end_date: '2020-03-30'
  initial_cash: 100000000
  save_full_trade_history: True  # True로 설정하면 모든 거래 내역을 CSV로 저장합니다.

# --- 3. Magic Split Strategy Parameters ---
strategy_params:
  max_stocks: 3
  order_investment_ratio: 0.04
  additional_buy_drop_rate: 0.01
  sell_profit_rate: 0.01
  additional_buy_priority: 'lowest_order'
  cooldown_period_days: 5 # 매도 후 재매수 방지 기간 (영업일 기준)

  # --- [New] Advanced Risk Management Parameters ---
  stop_loss_rate: -0.40 # 포지션 진입가 대비 최대 손실률 (-15%)
  max_splits_limit: 10 # 최대 분할매수 차수 (10차까지)
  max_inactivity_period: 90      # (정적) 최대 매매 미발생 기간 (일)

# --- 4. Execution Handler Parameters ---
execution_params:
  buy_commission_rate: 0.00015
  sell_commission_rate: 0.00015
  sell_tax_rate: 0.0018

# --- 5. Result & Log Paths ---
paths:
  results_dir: "results/"
  log_dir: "logs/"