# ===================================================================
# Magic Split Strategy - Global Configuration
# config.yaml
# ===================================================================

# --- 1. Database Connection ---
database:
  host: 172.21.224.1
  user: root
  password: "@waren2ss"
  database: stocks

# --- 2. Backtest Period & Capital ---
backtest_settings:
  start_date: '2014-08-01'
  end_date: '2025-05-30'
  initial_cash: 100000000
  save_full_trade_history: True  # True로 설정하면 모든 거래 내역을 CSV로 저장합니다.

# --- 3. Magic Split Strategy Parameters ---
strategy_params:
  max_stocks: 20
  order_investment_ratio: 0.026
  additional_buy_drop_rate: 0.067
  sell_profit_rate: 0.167
  additional_buy_priority: 'highest_drop'  # lowest_order
  cooldown_period_days: 5 # 매도 후 재매수 방지 기간 (영업일 기준)

  # --- [New] Advanced Risk Management Parameters ---
  stop_loss_rate: -0.50 # 포지션 진입가 대비 최대 손실률 (-15%)
  max_splits_limit: 15 # 최대 분할매수 차수 (10차까지)
  max_inactivity_period: 43     # (정적) 최대 매매 미발생 기간 (일)

# [추가] GPU 대량 시뮬레이션을 위한 파라미터 공간 정의
parameter_space:
  max_stocks:
    type: 'list'
    values: [20]
  order_investment_ratio:
    type: 'linspace'
    start: 0.02
    stop: 0.05
    num: 4 # 0.02, 0.03, 0.04, 0.05
  additional_buy_drop_rate:
    type: 'range'
    start: 0.04
    stop: 0.12 # 0.12는 포함되지 않음
    step: 0.02 # 0.04, 0.06, 0.08, 0.10
  sell_profit_rate:
    type: 'list'
    values: [0.14, 0.16, 0.18, 0.20, 0.22]
  additional_buy_priority:
    type: 'list' # 문자열 대신 숫자로 매핑 (0: lowest_order, 1: highest_drop)
    values: [1]
  stop_loss_rate:
    type: 'list'
    values: [-0.4, -0.5, -0.6, -0.7]
  max_splits_limit:
    type: 'list'
    values: [15]
  max_inactivity_period:
    type: 'range'
    start: 30
    stop: 181 # 181은 포함되지 않음
    step: 30 # 30, 60, 90, 120, 150, 180


# --- 4. Execution Handler Parameters ---
execution_params:
  buy_commission_rate: 0.00015
  sell_commission_rate: 0.00015
  sell_tax_rate: 0.0018

# --- 5. Result & Log Paths ---
paths:
  results_dir: "results/"
  log_dir: "logs/"

# ===================================================================
# 6. Walk-Forward Optimization Settings
# ===================================================================
walk_forward_settings:
  # [핵심] 사용자가 설정할 단 두 개의 변수
  total_folds: 5
  period_length_days: 2000 # IS와 OOS 기간의 길이를 '일' 단위로 지정 (예: 3년)